### ISSUE TITLE
Set 'ignore' within a source file

### ISSUE THREAD

**Issue by jek** [cburroughs/pep8.py#12]
It would be great to have comment-style pragmas to disable certain checks for a statement.  A simple global setting inside the file would be useful to start.

```
# pep8-ignore: E241
for spec in ((u'123',    123,  u'123'),
             (u' 123 ',  123,  u'123'),
             (u'xyz',    None, u'xyz')):
```

Or globally within a file:

```
# /usr/bin/python
# -*- coding: utf-8; pep-ignore: E241 -*-
```

**Comment by cburroughs** [comment]
I'm weary of turning pep8.py into a super powerful configurable tool like pylint.  We already have pylint and it's awesome.  

That said something like pylint's:  "#pylint: disable-msg=X0123" would be useful.  I'll think it over.

**Comment by ralphbean** [comment]
Any conclusions?  :)

**Comment by cburroughs** [comment]
Sorry, you need to be looking here https://github.com/jcrocholl/pep8
