### ISSUE TITLE
E231 should allow commas to be followed by )

### ISSUE THREAD

**Issue by ghost** [cburroughs/pep8.py#3]
E231 occurs with code such as:

cursor.execute(sql, (single_value,))

I believe that should be allowed, as (single_value, ) just looks worse and PEP-8 has no comment on this anyway.

**Comment by SmileyChris** [comment]
Fixed in http://github.com/SmileyChris/pep8.py/commit/15b908dd769dc578bf5e682f1e70b3565ac4f04d

**Comment by cburroughs** [comment]
This is addressed by jcrocholl's latest batch of changes. http://github.com/cburroughs/pep8.py/tree/merge-with-upstream
