### ISSUE TITLE
E302 is only reported the first time found

### ISSUE THREAD

**Issue by serverhorror** [cburroughs/pep8.py#4]
just run pep8 on the pep8.py itself and remove the 2 blank lines before tabs_or_spaces

First run:

```
$ python pep8.py pep8.py # reports line 119
pep8.py:119:1: E302 expected 2 blank lines, found 4
$ vim pep8.py
$ python pep8.py pep8.py # reports line 193
pep8.py:193:1: E302 expected 2 blank lines, found 4
```

**Comment by SmileyChris** [comment]
This isn't a bug: you need to use the `--repeat` argument to show a PEP error more than once.

**Comment by cburroughs** [comment]
SmileyChris is correct.  That said I know I almost always use `--repeat` myself.  It may make more sense as the default.

**Comment by SmileyChris** [comment]
I concur. Issue 6 created for this.
