### ISSUE TITLE
Make --repeat the default action

### ISSUE THREAD

**Issue by SmileyChris** [cburroughs/pep8.py#6]
I'm guessing we'd need a new flag like `--no-repeat` to allow for the current default behavior.

Would we deprecate or simply remove the `--repeat` argument?

**Comment by cburroughs** [comment]
+1 on `--no-repeat`.  I would prefer to deprecate `--repeat` for at least one release.  I'd also be interested in jcrocholl's opinion.

**Comment by florentx** [comment]
For new users of this module, I'm not sure it is useful to display a lot of lines the first  time they run the module on their code.

For advanced users, I would propose to support the short option `-r` in addition to `--repeat`.
I pushed this change on my branch.

**Comment by SmileyChris** [comment]
This was implemented back in 0.7.0 (6 years ago :))
