### ISSUE TITLE
method and class decorators must be allowed before class/def

### ISSUE THREAD

**Issue by reinout** [cburroughs/pep8.py#8]
The current blank_lines() check works OK for function decorators, but not for class and class method decorators.  I've added a test + fix for that (E301not.py) on my branch.

**Comment by reinout** [comment]
I added this after making the 0.4 release, btw.

**Comment by cburroughs** [comment]
Merged in.

**Comment by reinout** [comment]
OK if I just push out a new release? I kinda use those decorators a lot :-)

**Comment by reinout** [comment]
Hm. The 0.4.1 (and 0.4.0) have restructured text errors. I'm fixing that now and I'll to a 0.4.2.

**Comment by reinout** [comment]
Yep, 0.4.2 is OK now :-)
